## rename  Date time  create variables missing to cate delete  
## categorycal(rename + combine)

output$code.panel <- renderUI({
  code.panel.ui(get.data.set())
})

output$r.show.code <- renderUI({
  tags$div(style = "min-width: 80%;
                  white-space: nowrap;
                  display: inline-block;",
           verbatimTextOutput("r.code.history")      )
  
})

code.list <- reactive({
  do.call(c, lapply(code.save$variable, function(x) {
    return(x)
    y <- try({
      iNZightTools::tidy_all_code(
        paste(x, sep = "\n", collapse = "\n"),
        width = 80,
        indent = 4
      )
    }, silent = TRUE)
    if (inherits(y, "try-error")) x else c(y, "\n")
  }))
  
})


packages.call <- reactive({
  package.load <- c("iNZightPlots", "magrittr")
  if (any(grepl("::", code.list()))) {
    m <- regexpr("[a-zA-Z0-9]+::", code.list()[grepl("::", code.list())])
    pkg <- substr(code.list()[grepl("::", code.list())], m, m + attr(m, "match.length") - 3)
    for(i in 1:length(pkg)){
      if (!pkg[i] %in% package.load) package.load = c(package.load, pkg[i])
    }
  }
  if (any(grepl("library\\([a-zA-Z0-9]+\\)", code.list()))) {
      m <- regexpr("library\\([a-zA-Z0-9]+\\)", code.list())
      pkg <- gsub(".*library\\(|\\).*", "", substr(code.list(), m, m + attr(m, "match.length")))
      for(i in 1:length(pkg)){
        if (!pkg[i] %in% package.load) package.load = c(package.load, pkg[i])
      }
    }
  package.load
})


output$r.code.history <- renderText({
  c(" # iNZight Code History\n",
    "\n",
    "## This script was automatically generated by iNZight Lite\n",
    "\n",
    "## BETA WARNING: we're still working on making this as accurate\n",
    "##               as possible, so please ... \n",
    "##  - expect 'gaps' in the generated code (i.e., missing actions), and\n",
    "##  - LET US KNOW if you think something's missing\n",
    "##    (if you can give a minimal step-by-step to reproduce the problem, \n",
    "##     that would be incredibly useful!)\n",
    "##    email: inzight_support@stat.auckland.ac.nz\n",
    "\n",
    sep(),
    "\n",
    "## This script assumes you have various iNZight packages installed.\n",
    "## Uncomment the following lines if you don't:\n",
    "\n",
    paste0(sprintf("# install.packages(c('%s'), ", paste(packages.call(), collapse = "',\n #                    '")),"\n"),
    "#     repos = c('https://r.docker.stat.auckland.ac.nz',\n",
    "#               'https://cran.rstudio.com'))\n",
    "\n",
    sep(),
    "",
    code.list())
})
## initialize 
keep.last <- reactive(TRUE)


## add packages
#code <- gsub("\ +", " ", # one or more spaces with just one space!
#             paste(gsub(".dataset", code.save$name, code, fixed = TRUE), collapse = ""))
#code <- gsub(" %>% ", " %>% \n    ", code)
#asgnpipe <- paste(code.save$name, "%<>% ")
#gsub(paste0(code.save$name, " %>% \n    "), asgnpipe, code)

tidy_assign_pipe = function(code){
  code <- gsub("\ +", " ", # one or more spaces with just one space!
               paste(code, collapse = ""))
  gsub("%>%", "%<>%", code)
}
